Repository PHOENIXCONTACT/MORYX-ClientFramework, pull requests merged in 2020-10, with the labels that each got.

#14 Update GettingStarted.md
  docs/tutorials/GettingStarted.md
Labels: documentation

#17 Split of repository properties and common properties and package update
  .build/BuildToolkit.ps1
  .build/Common.props
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  src/Moryx.ClientFramework.Configurator/Moryx.ClientFramework.Configurator.csproj
  src/Moryx.ClientFramework.Kernel/Moryx.ClientFramework.Kernel.csproj
  src/Moryx.ClientFramework.SimpleShell/Moryx.ClientFramework.SimpleShell.csproj
  src/Moryx.ClientFramework.Tests.DialogManager/Moryx.ClientFramework.Tests.DialogManager.csproj
  src/Moryx.ClientFramework.Tests.HistoryWriter/Moryx.ClientFramework.Tests.HistoryWriter.csproj
  src/Moryx.ClientFramework.Tests.NotifyAndEditor/Moryx.ClientFramework.Tests.NotifyAndEditor.csproj
  src/Moryx.ClientFramework.Tests.Playground/Moryx.ClientFramework.Tests.Playground.csproj
  src/Moryx.ClientFramework/Moryx.ClientFramework.csproj
  src/Moryx.Controls.Demo/Moryx.Controls.Demo.csproj
  src/Moryx.Controls/Moryx.Controls.csproj
  src/Moryx.Tools.WcfClient.UI.Viewer/Moryx.Tools.WcfClient.UI.Viewer.csproj
  src/Tests/Moryx.ClientFramework.Kernel.Tests/Moryx.ClientFramework.Kernel.Tests.csproj
  src/Tests/Moryx.ClientFramework.Tests/Moryx.ClientFramework.Tests.csproj
Labels: enhancement

#18 Update wcf view model instead of remove and replace
  src/Moryx.Tools.WcfClient.UI.Viewer/Workspace/WcfClientInfoViewModel.cs
  src/Moryx.Tools.WcfClient.UI.Viewer/Workspace/WcfClientViewerWorkspaceViewModel.cs
Labels: bug
