Repository PHOENIXCONTACT/MORYX-ClientFramework, pull requests merged in 2020-11, with the labels that each got.

#19 Reintegrated logging into kernel and other bugs
  .build/BuildToolkit.ps1
  .build/Common.props
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  src/Controls4Industry/Controls4Industry.csproj
  src/Controls4Industry/ViewTemplates/DialogPanel/Generic.xaml
  src/Moryx.ClientFramework.Configurator/Moryx.ClientFramework.Configurator.csproj
  src/Moryx.ClientFramework.Kernel/Configuration/AppDataConfigManager.cs
  src/Moryx.ClientFramework.Kernel/Configuration/KernelConfigManager.cs
  src/Moryx.ClientFramework.Kernel/HeartOfLead.cs
  src/Moryx.ClientFramework.Kernel/Logging/ClientLoggerManagement.cs
  src/Moryx.ClientFramework.Kernel/Logging/CommonLoggingLogTarget.cs
  src/Moryx.ClientFramework.Kernel/Logging/LoggingConfig.cs
  src/Moryx.ClientFramework.Kernel/Moryx.ClientFramework.Kernel.csproj
  src/Moryx.ClientFramework.SimpleShell/Moryx.ClientFramework.SimpleShell.csproj
  src/Moryx.ClientFramework/Moryx.ClientFramework.csproj
  src/Moryx.Controls.Demo/Moryx.Controls.Demo.csproj
  src/Moryx.Controls.Demo/ViewModels/TemplatesViewModel.cs
  src/Moryx.Controls.Demo/Views/TemplatesView.xaml
  src/Moryx.Controls/Moryx.Controls.csproj
  src/Moryx.Tools.WcfClient.UI.Viewer/Moryx.Tools.WcfClient.UI.Viewer.csproj
  src/StartProject/Config/log4net.config
  src/StartProject/HeartOfLead.csproj.DotSettings
  src/StartProject/StartProject.csproj
  src/StartProject/app.config
Labels: bug, enhancement

#21 Final review of client docs
  docs/articles/Caliburn/CaliburnConventions.md
  docs/articles/ConfigManagers/AppDataConfigManager.md
  docs/articles/ConfigManagers/Configurations.md
  docs/articles/UI/Commands/AsyncCommand.md
  docs/articles/UI/ModalDialogs.md
  docs/articles/UI/ViewLocatorConfigurator.md
  docs/articles/index.md
  docs/tutorials/GettingStarted.md
  docs/tutorials/Themes.md
Labels: documentation

#23 Usage of dotnet instead of msbuild and .net5.0 tfm
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  README.md
  src/Moryx.WpfToolkit/Moryx.WpfToolkit.csproj
Labels: enhancement

#22 Fixed behavior of removal and replace buttons for read only entries
  src/Moryx.Controls.Demo/Models/EntryClass.cs
  src/Moryx.Controls/EntryEditor/Converter/EntryTypeToDelButtonVisibilityConverter.cs
  src/Moryx.Controls/EntryEditor/Converter/EntryValueToVisibilityConverter.cs
  src/Moryx.Controls/EntryEditor/EntryEditor.xaml.cs
  src/Moryx.Controls/EntryEditor/EntryViewModel.cs
Labels: bug
